import { Inter } from "next/font/google";
import "./globals.css";
// import { SessionProvider } from "next-auth/react";
import SessionProvider from "./components/SessionProvider"; //next SessionProvider imported
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const session = getServerSession();

  return (
    <SessionProvider session={"dd"}>
      <html lang="en">
        <body suppressHydrationWarning={true} className={inter.className}>
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
